# Generated by Django 2.1.7 on 2019-03-27 18:16

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190324_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.get_path),
        ),
    ]
