# Generated by Django 2.1.7 on 2019-03-27 19:46

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190327_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=post.models.get_path),
        ),
    ]
